server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mp?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: cz13985150811

logging:
  level:
    #根日志 ： 级别
    root: debug
    # dao包 ： 级别
    com.example.mp.dao: trace
  #格式 %p日志级别  %m日志内容 %n换行
  pattern:
    console: '%p  %m%n'

#配置扫描xml文件
mybatis-plus:
  mapper-locations:
  - com/example/mp/mapper/*

